load("//:copts.bzl", "RSR_DEFAULT_COPTS")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "algorithm",
    srcs = ["rclr_algorithm.cxx"],
    hdrs = ["rclr_algorithm.hxx"],
    copts = RSR_DEFAULT_COPTS,
    )
